#!/bin/bash

while getopts  "c:w:" flag
do
  case "$flag" in
  "c") 
    COMMANDS="$COMMANDS($OPTARG)"
    echo $COMMANDS
    ;;
  "w")
    WINDOW_XID=$OPTARG
    ;;
  esac
done
    echo $OPTIND $OPTARG


cat <<EOF >/tmp/devilspie-wrapper.$$
(if
  (is (str (window_xid))  "$WINDOW_XID")
     $COMMANDS
    )
)
(quit)
EOF

devilspie -a -d /tmp/devilspie-wrapper.$$

rm /tmp/devilspie-wrapper.$$
