#!/bin/bash

#sudo /sbin/initctl emit --no-wait yavdr-desktop-session-start DISPLAY=$DISPLAY USER=$USER HOME=$HOME
python /usr/share/yavdr-desktop/main.py -l ~/.yavdr-desktop.log
/usr/bin/yavdr-applauncherd &
