#!/usr/bin/env python

import wnck
import gtk
import optparse
#import pyatspi
import syslog
### new imports ###
import dbus
import uinput
import socket
import string
import gobject
import itertools
import ConfigParser
import os

class DesktopHelperConfig:

    def __init__(self):
        self.config = ConfigParser.ConfigParser()
        self.config.read(['/etc/yavdr-desktop/yavdr-wm.conf', os.path.expanduser('~/.yavdr-wm.conf')])
        self.config = dict(self.getConfigSections())
        self.windows = dict(self.getDictForType('window'))
        self.applications = dict(self.getDictForType('application'))
        self.classes = dict(self.getDictForType('class'))

    def getConfigOptions(self, section):
        for option in self.config.options(section):
            yield option, self.config.get(section, option)

    def getConfigSections(self):
        for section in self.config.sections():
            yield section, dict(self.getConfigOptions(section))

    def getDictForType(self, type):
        for section, option in self.config.items():
            if 'type' in option and option['type'] == type and 'name' in option:
                yield option['name'], option

class DesktopHelper(object):
    def __init__(self, config):
        self.config = config
        self.remote = self.create_dbus_remoteHandler()
        Lircd2Any = lircd2any('/var/run/lirc/lircd', 'lirc') # use None to disable remote at startup, 'lirc' for lirc-Socket, 'uinput' for virtual event device
               
        screen = wnck.screen_get_default()
        screen.connect("active-window-changed", self.on_active_window_changed)
        screen.connect("window-opened", self.on_window_opened)
    
    def match_window(self, window):
        return window.get_name() in self.config.windows or \
            window.get_application().get_name() in self.config.applications or \
            window.get_class_group().get_res_class() in self.config.classes
		   
    def undecorate_and_maximize(self, window):
        syslog.syslog("undecorate window: " + window.get_name())
        command = "devilspie-wrapper -w " + window.get_xid() + " -c undecorate -c maximize"
        os.system(command)
        '''xwindow = gtk.gdk.window_foreign_new(window.get_xid())
        xwindow.set_decorations(0)
        window.maximize()'''

    def on_active_window_changed (self, screen, previous):
        active = screen.get_active_window()
        syslog.syslog("window " + active.get_name() + " got active")
        if active and active is not None:
            if self.match_window(active):
                self.undecorate_and_maximize(active)

    def on_window_opened (self, screen, window):
        syslog.syslog("window " + window.get_name() + " was opened")
        if self.match_window(window):
            self.undecorate_and_maximize(window)

    '''def pressKey(self, keycode):
        """Takes an integer keycode. You can find these with xev."""
        pyatspi.Registry.generateKeyboardEvent(keycode, None,
                                              pyatspi.KEY_PRESSRELEASE)'''
                                              
    def create_dbus_remoteHandler(self):
        '''Create dbus handler for vdr dbus remote'''
        bus = dbus.SystemBus()
        proxy_obj = bus.get_object("de.tvdr.vdr", "/Remote")
        remote = dbus.Interface(proxy_obj, "de.tvdr.vdr.remote")
        return remote
    
    ''' Example functions to control if VDR reacts to remote events '''
    def remote_status(self):
        # get current remote status
        return self.remote.Status()
    
    def disableRemote(self):
        self.remote.Disable()
        
    def enableRemote(self):
        self.remote.Enable()
        
class lircd2any():

    def __init__(self,socket_path, activeout):
        self.sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)   
        self.sock.connect(socket_path)
        self.OutputDevs = {}
        self.add_output_device()
        self.add_output_device('lirc','lirc',socket_path='/var/run/lirc/bridge')
        self.active_output = None
        self.set_active_output(activeout)
        syslog.syslog("Listening to %s..." %(socket_path))
        gobject.io_add_watch(self.sock, gobject.IO_IN, self.handler)

    def handler(self, sock, *args):
        '''Asynchronous connection handler. Processes each line from the socket.'''
        buf = sock.recv(1024)
        lines = string.split(buf, "\n")
        for line in lines[:-1]:
          code,count,cmd,device = string.split(line, " ")
          self.output(code, count, cmd, device)
          return True

    def output(self, code, count, cmd, device):
        #print " ".join([code, count, cmd, device])
        if self.active_output != None:
            self.active_output.send_key(code, count, cmd, device)

    def set_active_output(self, device):
        if device == 'None' or device == None:
            self.active_output = None

        else:
            try:
                self.active_output = self.OutputDevs[device]
            except:
                syslog.syslog('No matching device for %s found, setting to None' %(device))
                self.active_output = None

    def add_output_device(self, devicename='uinput', devicetype='uinput', match=['KEY_'], socket_path='/var/run/lirc/bridge'):
        print ('test1')
        self.OutputDevs[devicename] = OutputDev(devicename,devicetype,match,socket_path)
        print ('test2')


class OutputDev():
  
    def __init__(self, devicename='uinput',devicetype='uinput',match=['KEY_','BTN_','REL_'],socket_path='/var/run/lirc/bridge'):    
        self.devicetype = devicetype    
        if devicetype == 'uinput':
            self.events = self.select_capabilities(match)
            self.device = uinput.Device(self.events, devicename)
        if devicetype == 'lirc':
            self.device = self.create_lircd_socket(socket_path)
            self.conns = []

    def select_capabilities(self,match):
        keys = []
        items = dir(uinput)
        for item in itertools.product(match,items):
            if item[1].startswith(item[0]):
                keys.append(eval('uinput.%s'%(item[1])))
        return keys

    def create_lircd_socket(self, socket_path):
        try:
            os.remove(socket_path)
        except OSError:
            pass
        sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        sock.bind(socket_path)
        sock.listen(5)
        gobject.io_add_watch(sock, gobject.IO_IN, self.listener)
        syslog.syslog("created Lirc-Socket %s"%(socket_path))
        return sock

    def listener(self, sock, *args):
        conn,a = sock.accept()
        self.conns.append(conn)
        syslog.syslog("Connected to %s" %(conn))
        return True


    def send_key(self, code, count, cmd, device):
        if self.devicetype == 'uinput':
            self.device.emit(eval('uinput.%s'%(cmd)),1)
            self.device.emit(eval('uinput.%s'%(cmd)),0)
        if self.devicetype == 'lirc' and len(self.conns) > 0:
            for conn in self.conns:
                try:
                    conn.send("%s\n"%" ".join([code, count, cmd, device]))
                except: # garbage collection for lost clients - any better idea?
		    syslog.syslog("cannot write to connection %s, removing client connection"%(conn))
                    conn.close()
                    self.conns.pop(self.conns.index(conn))


def getOptions():          
    parser = optparse.OptionParser()

    parser.add_option('-t', '--title', metavar='TITLE', action='append',
        dest='title_matches', help='Match window title')
    
    options, args = parser.parse_args()
    return options,args

def main():
    options, args = getOptions()
    dhc = DesktopHelperConfig()
    print(dhc.windows)
    print(dhc.applications)
    print(dhc.classes)
    dh = DesktopHelper(dhc)
    print ('TEST')
    
	# This is a standard GTK mechanism, which is required to capture all existing events
    while gtk.events_pending():   
        gtk.main_iteration()
        
    gtk.main()

if __name__ == '__main__':
    main()
