#!/bin/bash

if [ $# -lt 1 ]
then
  echo "usage: $0 app"
  exit 1
fi

DEST=org.yavdr.applauncher
OBJECT=/launcher
INTERFACE=launchApp

dbus-send --system --type=method_call --dest=$DEST --print-reply $OBJECT $DEST.$INTERFACE "string:'$@'"
