#!/bin/bash

#set -x

PRIMARY=0
SECONDARY=0
OTHER=0

while getopts "d:pso" opt; do
  case $opt in
    d)
      DEVID=$OPTARG
      ;;
    p)
      PRIMARY=1
      DISPLAY=0
      ;;
    s)
      SECONDARY=1
      DISPLAY=1
      ;;
    o)
      OTHER=1
      ;;
  esac
done

if [ $OTHER -eq 0 ]; then
  RES=`dbget system.x11.display.$DISPLAY.resolution`
  RATE=`dbget system.x11.display.$DISPLAY.defaultrate`

  xrandr --output $DEVID --mode $RES --rate $RATE
  if [ $PRIMARY -eq 1 ]; then
    xrandr --output $DEVID --primary
  else
    xrandr --output $DEVID  --right-of `dbget system.x11.display.0.device`
  fi
else
  # just activate the display  xrandr --output $DEVID --auto
fi

