#!/bin/bash

LIRCD_CONF="$(dbget system.remote.lirc.receiver.lircd_conf)"

if [ "$(dbget system.remote.lirc.active)" = "1" ]; then
  if [ -n "$LIRCD_CONF" ]; then
    rm -f /etc/lirc/lircd.conf
    if [ -e /usr/share/lirc/remotes/$LIRCD_CONF ]; then
      ln -sf /usr/share/lirc/remotes/$LIRCD_CONF /etc/lirc/lircd.conf
    elif [ -e /usr/share/lirc/extras/more_remotes/$LIRCD_CONF ]; then
      ln -sf /usr/share/lirc/extras/more_remotes/$LIRCD_CONF /etc/lirc/lircd.conf
    fi
  elif [ -L /etc/lirc/lircd.conf ]; then 
    rm -f /etc/lirc/lircd.conf
  fi
fi
 
if grep -q "^REMOTE_MODULES.*lirc_serial.*" /etc/lirc/hardware.conf ; then 
   rmmod lirc_serial
   start setserial-minimal
   modprobe lirc_serial
else 
   rm -f /etc/modprobe.d/lirc-serial.conf 
fi 
