#!/bin/bash

#set -x

while getopts "d:" opt; do
  case $opt in
    d)
      DEVID=$OPTARG
      ;;
  esac
done

if [ -z $DEVID ]; then
  logger "Device is missing"
  exit 1;
fi

# detect display
if [ `dbget system.x11.display.0.device` = "$DEVID" ]; then
  OPTION="-p"          # primary
elif [ `dbget system.x11.display.1.device` = "$DEVID" ]; then
  OPTION="-s"        # seconday
else
  OPTION="-o"        # other
fi

run-parts --verbose -a "-d" -a "$DEVID" -a "$OPTION" /usr/share/yavdr/xrandr-eventd/on.d
