#!/bin/bash

if [ "x$(dbget system.sound.type)" = "xhdmi" ] || \
   [ "x$(dbget system.sound.type)" = "xanalog" ] || \
   [ "x$(dbget system.sound.type)" = "x" ] ; then
vdr-dbus-send /Setup setup.Set string:'xineliboutput.Audio.Speakers' variant:string:'Stereo 2.0' &> /dev/null
vdr-dbus-send /Setup setup.Set string:'softhddevice.AudioPassthrough' variant:string:'0' &> /dev/null
vdr-dbus-send /Setup setup.Set string:'softhddevice.AudioDownmix' variant:string:'1' &> /dev/null
elif [ "x$(dbget system.sound.type)" = "xpassthrough" ] || \
     [ "x$(dbget system.sound.type)" = "xspdif" ] ; then
vdr-dbus-send /Setup setup.Set string:'xineliboutput.Audio.Speakers' variant:string:'Pass Through' &> /dev/null
vdr-dbus-send /Setup setup.Set string:'softhddevice.AudioPassthrough' variant:string:'1' &> /dev/null
vdr-dbus-send /Setup setup.Set string:'softhddevice.AudioDownmix' variant:string:'0' &> /dev/null

fi

