#!/bin/bash
ORDER_CONF=/etc/vdr/plugins/order.conf
#ORDER_CONF=order.conf

PLUGIN=`echo $3 | cut -f3- -d- -`

append_plugin () {
  echo $1 >> $ORDER_CONF
}

enable_plugin () {
		vdrctl enable "$1" 2>&1 >> /tmp/change-frontend
}

disable_plugin () {
		vdrctl disable "$1" 2>&1 >> /tmp/change-frontend

}

if [ "$2" = "enable" ]; then
  enable_plugin $PLUGIN
elif [ "$2" = "disable" ]; then
  disable_plugin $PLUGIN
  
  if [ "x$(dbget vdr.plugin.graphtft.enabled)" = "x1" -a "$PLUGIN" = "graphtftng" ]; then
    dbset "vdr.plugin.graphtft.enabled=0"
  fi
fi
