#!/bin/bash

enable_plugin () {
		vdrctl enable "$1" 2>&1 >> /tmp/change-remoted
}

disable_plugin () {
		vdrctl disable "$1" 2>&1 >> /tmp/change-remoted
}

REMOTE=`dbget system.remoted`

if [ "x$REMOTE" = "x" -o "x$REMOTE" = "xlircd" ]; then
  /usr/bin/signal-event change-remote-hardware
else
  restart remoted
fi

if [ "x$REMOTE" = "xvdrremote" ]; then
  enable_plugin "remote"
else
  disable_plugin "remote"
fi
