#!/bin/bash

LIRCD="$(dbget system.remoted)"
LIRCD_CONF="$(dbget system.lirchw.lircd_conf)"


if [ "$LIRCD" = "lircd" ]; then
  if [ -n "$LIRCD_CONF" ]; then
    rm -f /etc/lirc/lircd.conf
    if [ -e /usr/share/lirc/remotes/$LIRCD_CONF ]; then
      ln -sf /usr/share/lirc/remotes/$LIRCD_CONF /etc/lirc/lircd.conf
    elif [ -e /usr/share/lirc/extras/more_remotes/$LIRCD_CONF ]; then
      ln -sf /usr/share/lirc/extras/more_remotes/$LIRCD_CONF /etc/lirc/lircd.conf
    fi
  elif [ -L /etc/lirc/lircd.conf ]; then 
    rm -f /etc/lirc/lircd.conf
  fi
else 
  rm -f /etc/modprobe.d/lirc-serial.conf
fi 

 

MODULE=""
for MODULE in `dbget system.lirchw.driver` ; do
    modprobe -r $MODULE
    modprobe $MODULE
fi 

