#!/bin/bash

enable_plugin () {
		vdrctl enable "$1" 2>&1 >> /tmp/change-frontend
}

disable_plugin () {
		vdrctl disable "$1" 2>&1 >> /tmp/change-frontend

}

if [ "$(dbget vdr.backend)" = "xineliboutput" ]; then
  enable_plugin "xineliboutput"
  disable_plugin "dvbhddevice"
  disable_plugin "dvbsddevice"
  disable_plugin "pvr350"
  disable_plugin "softhddevice"
  disable_plugin "xine"
#  disable_plugin "dummydevice"
#  enable_plugin "menuorg"
#  enable_plugin "yaepghd"
#  enable_plugin "suspendoutput"
#  enable_plugin "imonlcd"
#  enable_plugin "lcdproc"
#  enable_plugin "dynamite"

elif [ "$(dbget vdr.backend)" = "xine" ]; then
  enable_plugin "xine"
  disable_plugin "dvbhddevice"
  disable_plugin "dvbsddevice"
  disable_plugin "pvr350"
  disable_plugin "softhddevice"
  disable_plugin "xineliboutput"
#  disable_plugin "dummydevice"
#  enable_plugin "menuorg"
#  enable_plugin "yaepghd"
#  enable_plugin "suspendoutput"
#  enable_plugin "imonlcd"
#  enable_plugin "lcdproc"
#  enable_plugin "dynamite"

elif [ "$(dbget vdr.backend)" = "softhddevice" ]; then
  enable_plugin "softhddevice"
  disable_plugin "dvbhddevice"
  disable_plugin "dvbsddevice"
  disable_plugin "pvr350"
  disable_plugin "xine"
  disable_plugin "xineliboutput"
#  disable_plugin "dummydevice"
#  enable_plugin "menuorg"
#  enable_plugin "yaepghd"
#  enable_plugin "xvdr"
#  enable_plugin "suspendoutput"
#  enable_plugin "imonlcd"
#  enable_plugin "lcdproc"
#  enable_plugin "dynamite"

elif [ "$(dbget vdr.backend)" = "streaming" ]; then
  disable_plugin "dvbhddevice"
  disable_plugin "dvbsddevice"
  disable_plugin "pvr350"
  disable_plugin "softhddevice"
  disable_plugin "xine"
  disable_plugin "xineliboutput"
#  enable_plugin "streamdev-server"
#  enable_plugin "vnsiserver"
#  enable_plugin "dummydevice"
#  disable_plugin "lcdproc"
#  disable_plugin "imonlcd"
#  disable_plugin "menuorg"
#  disable_plugin "yaepghd"
#  disable_plugin "suspendoutput"
#  enable_plugin "dynamite"

elif [ "$(dbget vdr.backend)" = "hdff" ] || [ "$(dbget vdr.backend)" = "sdff" ]; then
  if [ "$(dbget vdr.backend)" = "sdff" ]; then
    enable_plugin "dvbsddevice"
    disable_plugin "dvbhddevice"
  else
    enable_plugin "dvbhddevice"
    disable_plugin "dvbsddevice"
  fi
  disable_plugin "pvr350"
  disable_plugin "softhddevice"
  disable_plugin "xine"
  disable_plugin "xineliboutput"
#  disable_plugin "dummydevice"
#  enable_plugin "dynamite"
#  enable_plugin "lcdproc"
#  enable_plugin "imonlcd"
#  #enable_plugin "iptv"
#  enable_plugin "menuorg"
#  enable_plugin "yaepghd"
#  enable_plugin "suspendoutput"

elif [ "$(dbget vdr.backend)" = "pvr350" ]; then

if ! grep '^ivtv' /etc/modules > /dev/null; then
  echo "ivtv" >> /etc/modules
  echo "ivtvfb" >> /etc/modules
  echo "ir_kbd_i2c" >> /etc/modules
fi

  enable_plugin "pvr350"
  disable_plugin "dvbhddevice"
  disable_plugin "dvbsddevice"
  disable_plugin "softhddevice"
  disable_plugin "xine"
  disable_plugin "xineliboutput"
#  disable_plugin "dummydevice"
#  enable_plugin "iptv"
#  enable_plugin "dynamite"
#  enable_plugin "lcdproc"
#  enable_plugin "imonlcd"
#  enable_plugin "menuorg"
#  enable_plugin "yaepghd"

fi

if [ ! "$(dbget vdr.backend)" = "pvr350" ]; then
 sed -i /"^ivtv"/d /etc/modules
 sed -i /"^ir_kbd_i2c"/d /etc/modules
fi

# graphtft support
if [ "x$(dbget vdr.plugin.graphtft.enabled)" = "x1" ]; then
  enable_plugin "graphtftng"
else
  disable_plugin "graphtftng"
fi

# disable vdr if needed
process-template /etc/init/vdr.override
