#!/bin/bash

alsa=`dbget system.sound.alsa`
card=`expr match "$alsa" '.*\:CARD\=\(.*\),.*'`
dev=`expr match "$alsa" '.*,DEV\=\(.*\)'`
dbset system.sound.alsacard=$card
dbset system.sound.alsadevice=$dev

process-template /etc/asound.conf
process-template /etc/init/pulseaudio.override
process-template /etc/init/pavucontrol.conf
process-template /usr/share/pulseaudio/alsa-mixer/profile-sets/extra-hdmi.conf
