#!/bin/bash

alsa=`dbget system.sound.alsa`
card=`expr match "$alsa" '.*\:CARD\=\(.*\),.*'`
dev=`expr match "$alsa" '.*,DEV\=\(.*\)'`
dbset system.sound.alsacard=$card
dbset system.sound.alsadevice=$dev

process-template /etc/asound.conf
process-template /etc/init/pulseaudio.override
process-template /etc/init/pavucontrol.conf
process-template /usr/share/pulseaudio/alsa-mixer/profile-sets/extra-hdmi.conf
process-template --owner=vdr --group=vdr /var/lib/vdr/plugins/menuorg.xml
if [[ $(dbget system.sound.type) == pulse ]]; then
    start pulseaudio
    vdrctl enable pulsecontrol 2>&1 >> /tmp/create-asound-conf
 else
    stop pulseaudio
    vdrctl disable pulsecontrol 2>&1 >> /tmp/create-asound-conf
fi
