#!/bin/bash

process-template --mode=755 --owner=vdr --group=vdr /usr/bin/removemarks
process-template --mode=755 --owner=vdr --group=vdr /usr/bin/removeindex
process-template --mode=755 --owner=vdr --group=vdr /usr/bin/vdr-recrepeat

