#!/bin/bash

  if [ "x$(dbget vdr.deinterlacer.hd.type)" = "xbob" ] ; then

     vdr-dbus-send /Setup setup.Set string:'softhddevice.1080i.Deinterlace' variant:string:'0' &> /dev/null
     vdr-dbus-send /Setup setup.Set string:'softhddevice.720p.Deinterlace' variant:string:'0' &> /dev/null
     vdr-dbus-send /Setup setup.Set string:'softhddevice.1080i_fake.Deinterlace' string:'0' &> /dev/null

elif [ "x$(dbget vdr.deinterlacer.hd.type)" = "xtemporal" ] || \
     [ "x$(dbget vdr.deinterlacer.hd.type)" = "xhalf temporal" ] ; then

     vdr-dbus-send /Setup setup.Set string:'softhddevice.1080i.Deinterlace' variant:string:'2' &> /dev/null
     vdr-dbus-send /Setup setup.Set string:'softhddevice.720p.Deinterlace' variant:string:'2' &> /dev/null
     vdr-dbus-send /Setup setup.Set string:'softhddevice.1080i_fake.Deinterlace' variant:string:'2' &> /dev/null

elif [ "x$(dbget vdr.deinterlacer.hd.type)" = "xtemporal_spatial" ] || \
     [ "x$(dbget vdr.deinterlacer.hd.type)" = "xhalf temporal_spatial" ] ; then

     vdr-dbus-send /Setup setup.Set string:'softhddevice.1080i.Deinterlace' variant:string:'3' &> /dev/null
     vdr-dbus-send /Setup setup.Set string:'softhddevice.720p.Deinterlace' variant:string:'3' &> /dev/null
     vdr-dbus-send /Setup setup.Set string:'softhddevice.1080i_fake.Deinterlace' variant:string:'3' &> /dev/null

  fi

  if [ "x$(dbget vdr.deinterlacer.sd.type)" = "xbob" ] ; then

     vdr-dbus-send /Setup setup.Set string:'softhddevice.576i.Deinterlace' variant:string:'0' &> /dev/null

elif [ "x$(dbget vdr.deinterlacer.sd.type)" = "xtemporal" ] || \
     [ "x$(dbget vdr.deinterlacer.sd.type)" = "xhalf temporal" ] ; then

     vdr-dbus-send /Setup setup.Set string:'softhddevice.576i.Deinterlace' variant:string:'2' &> /dev/null

elif [ "x$(dbget vdr.deinterlacer.sd.type)" = "xtemporal_spatial" ] || \
     [ "x$(dbget vdr.deinterlacer.sd.type)" = "xhalf temporal_spatial" ] ; then

     vdr-dbus-send /Setup setup.Set string:'softhddevice.576i.Deinterlace' variant:string:'3' &> /dev/null

  fi
