#!/bin/bash
# detect helper
check_pci() {
  lspci -nv | grep -i -q "Subsystem: $1"
}

# skip driver autoinstall for some older nvidia cards:
for nvidia_pci_id in "10de:0848" "10de:0849" "10de:0876"; do
    check_pci "$nvidia_pci_id" && exit 0
done
# autoinstall recommended drivers
ubuntu-drivers autoinstall
