#!/bin/bash

if [[ "$(imvirt)" == "VirtualBox" ]]; then
  apt-get install -y virtualbox-guest-dkms virtualbox-guest-x11 dkms
  dbset vdr.setup=sxfe
  dbset vdr.frontend=sxfe
  dbset vdr.backend=xineliboutput
fi
