#!/bin/bash

############################################################################################################
# hardware detection for yavdr
# author: Marco Scholl <yavdr@marco-scholl.de>
############################################################################################################

# detect helper
check_pci() {
  lspci -nv | grep -i -q "Subsystem: $1"
}

check_pci2() {
  lspci -n | awk '{ print $3 }' | grep -i -q "$1"
}

check_usb() {
  lsusb | grep -i -q "$1"
}

check_module() {
  lsmod | grep -q "$1"
}

############################################################################################################

# default channels.conf
SOURCE="IP"

# detect only one dvb tree
DRIVER=""

############################################################################################################
# erkenne erstmal geräte die mit beiden paketen laufen und mindest einen davon benötigen
# die DRIVER variable kann dann von nachfolgenden erkennungen überschrieben werden
############################################################################################################

# TT 6400 PCI
if check_pci "13c2:300a" || check_pci "13c2:300b"; then
  # ist kein treiber gewählt, so installiere den v4l
  SOURCE="SAT"
  DRIVER="linux-media-dkms"
  dbset vdr.setup="hdff"
  dbset vdr.frontend="disabled"
  dbset vdr.backend="hdff"
  /usr/bin/signal-event change-frontend

# SD-FFs
elif check_module "dvb-ttpci" || check_module "dvb_ttpci" ; then
  dbset vdr.setup="custom"
  dbset vdr.frontend="disabled"
  dbset vdr.backend="sdff"
  /usr/bin/signal-event change-frontend

# PVR350
elif check_pci "0070:4000" ; then
  dbset vdr.setup="custom"
  dbset vdr.frontend="disabled"
  dbset vdr.backend="pvr350"
  /usr/bin/signal-event change-frontend
fi

############################################################################################################
# erkenne nun nach priorität treiber vorraussetzungen
############################################################################################################

# DVBWorld DVB-S2 PCIE2006
if check_pci "1ADE:2032"; then
  SOURCE="SAT"
  DRIVER="linux-media-dkms"
fi

# Digital Devices, Satix
if  check_pci "18c3:abc3" \
 || check_pci "18c3:abc4" \
 || check_pci "18c3:ab04" \
 || check_pci "18c3:dd00" \
 || check_pci "18c3:ab05" \
 || check_pci "18c3:dd10" \
 || check_pci "18c3:dd20" \
 || check_pci "18c3:db01" \
 || check_pci "18c3:db02" \
 || check_pci "dd01:0001" \
 || check_pci "dd01:0002" \
 || check_pci "dd01:0004" \
 || check_pci "dd01:0010" \
 || check_pci "dd01:0011" \
 || check_pci "dd01:0020" \
 || check_pci "dd01:0021" \
 || check_pci "dd01:0030" \
 || check_pci "dd01:0040" \
 || check_pci "dd01:db03" ; then
  SOURCE="S2/C/T"
  DRIVER="media-build-experimental-dkms"
fi

# detect: Hauppauge 930c
if  check_usb "2040:1605" ; then
  SOURCE="C"
  DRIVER="media-build-experimental-dkms"
fi


# install driver
if [ -n "$DRIVER" ]; then
  apt-get install -y $DRIVER
fi

# detect: Sundtek Sticks
if check_usb "eb1a:5"; then
  apt-get install -y yavdr-hardware-sundtek
fi



# todo set channels
#echo $SOURCE
process-template /etc/init/first-vdr-start.conf
