#!/bin/bash

############################################################################################################
# hardware detection for yavdr
# author: Alexander Grothe <seahawk1986@hotmail.com>
############################################################################################################

# detect helper


check_usb() {
lsusb | grep -i -q "$1"
}


############################################################################################################

# detect: USB - CEC Adapter pulse-eight.com

if check_usb "2548:1002"; then
apt-get install -y libcec-daemon
fi
