#!/bin/bash

if [ -e /etc/default/locale ]; then
. /etc/default/locale
fi

export LANG

mkdir -p /var/lib/vdr/.xbmc/userdata/Database/
mkdir -p /var/lib/vdr/.xbmc/userdata/keymaps

sqlite3  /var/lib/vdr/.xbmc/userdata/Database/TV19.db<<EOF
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE version (idVersion integer, iCompressCount integer);
INSERT INTO "version" VALUES(19,0);

CREATE TABLE clients (idClient integer primary key, sName    varchar(64), sUid     varchar(32));
INSERT INTO "clients" VALUES(1,'VDR XVDR Client','pvr.vdr.xvdr');

CREATE TABLE channels (idChannel            integer primary key, iUniqueId            integer, bIsRadio             bool, bIsHidden            bool, sIconPath            varchar(255), sChannelName         varchar(64), bIsVirtual           bool, bEPGEnabled          bool, sEPGScraper          varchar(32), iLastWatched         integer,iClientId            integer, iClientChannelNumber integer, sInputFormat         varchar(32), sStreamURL           varchar(255), iEncryptionSystem    integer, idEpg                integer);

CREATE TABLE channelgroups (idGroup    integer primary key,bIsRadio   bool, sName      varchar(64));
INSERT INTO "channelgroups" VALUES(1,1,'All radio channels');

CREATE TABLE map_channelgroups_channels (idChannel      integer, idGroup        integer, iChannelNumber integer);

CREATE TABLE channelsettings (idChannel            integer primary key, iInterlaceMethod     integer, iViewMode            integer, fCustomZoomAmount    float, fPixelRatio          float, iAudioStream         integer, iSubtitleStream      integer,fSubtitleDelay       float, bSubtitles           bool, fBrightness          float, fContrast            float, fGamma               float,fVolumeAmplification float, fAudioDelay          float, bOutputToAllSpeakers bool, bCrop                bool, iCropLeft            integer, iCropRight           integer, iCropTop             integer, iCropBottom          integer, fSharpness           float, fNoiseReduction      float, fCustomVerticalShift float, bCustomNonLinStretch bool, bPostProcess         bool, iScalingMethod       integer, iDeinterlaceMode     integer );

CREATE UNIQUE INDEX idx_channels_iClientId_iUniqueId on channels(iClientId, iUniqueId);
CREATE INDEX idx_channelgroups_bIsRadio on channelgroups(bIsRadio);
CREATE UNIQUE INDEX idx_idGroup_idChannel on map_channelgroups_channels(idGroup, idChannel);

COMMIT;
EOF

sqlite3  /var/lib/vdr/.xbmc/userdata/Database/Addons15.db<<EOF
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE version (idVersion integer, iCompressCount integer);
INSERT INTO "version" VALUES(15,0);
CREATE TABLE enabled (id integer primary key, addonID text);
INSERT INTO "enabled" VALUES(1,'pvr.vdr.xvdr');
CREATE UNIQUE INDEX idxEnabled ON enabled(addonID);
COMMIT;
EOF


chown -R vdr:vdr /var/lib/vdr/.xbmc

process-template --owner=vdr --group=vdr /var/lib/vdr/.xbmc/userdata/sources.xml
process-template --owner=vdr --group=vdr /var/lib/vdr/.xbmc/userdata/Lircmap.xml
process-template --owner=vdr --group=vdr /var/lib/vdr/.xbmc/userdata/guisettings.xml
process-template --owner vdr --group vdr /var/lib/vdr/.xbmc/userdata/keymaps/remote.xml

