#!/bin/bash

rm -f /etc/asound.conf
for INTERFACE in hdmi digital analog ; do
CARD=""
DEVICE=""

if [ $(LANG=C aplay -l | grep -i $INTERFACE | wc -l) -eq 1 ]; then
  SINK="$(LANG=C aplay -l | grep -i $INTERFACE)"
  # get the index id's
  CARD=${SINK//card } ; CARD=${CARD%%:*}
  DEVICE=${SINK//*device }; DEVICE=${DEVICE%%:*}

  # put them into db
  dbset system.hardware.alsa.${INTERFACE}.card=$CARD
  dbset system.hardware.alsa.${INTERFACE}.device=$DEVICE
elif [ $(LANG=C aplay -l | grep -i $INTERFACE | wc -l) -gt 1 ]; then
  CARD=$(LANG=C aplay -l | grep -i $INTERFACE) ; CARD=${CARD//:*} ; CARD=${CARD#card }
  ELD="`grep -e "monitor_present.*1$" /proc/asound/card${CARD}/eld* | cut -d":" -f1`"
  if [ "x$ELD" != "x" ]; then
    ELD=${ELD#*\#} ; ELD=${ELD//.*}
    #DEVICE=$(grep -e "^ *Device:.*" /proc/asound/card$CARD/codec\#${ELD})
    DEVICE=$(grep -e ".*ELD.*" /proc/asound/card$CARD/codec\#${ELD})
    DEVICE=${DEVICE#*device=}

    # put them into db
    dbset system.hardware.alsa.${INTERFACE}.card=$CARD
    dbset system.hardware.alsa.${INTERFACE}.device=$DEVICE
  else
    # we are totally lost and need to do some wild guessing
    dbset system.hardware.alsa.${INTERFACE}.card=$CARD
    dbset system.hardware.alsa.${INTERFACE}.device=7
  fi
fi
done

if [ "$(dbget system.sound.type)" = "" ]; then
   if [ "$(dbget system.hardware.alsa.hdmi.device)"    != "" -a \
        "$(dbget system.hardware.alsa.digital.device)" != "" -a \
        "$(dbget system.hardware.alsa.analog.device)"  != "" ]; then
      dbset system.sound.type="all"
   elif  [ "$(dbget system.hardware.alsa.hdmi.device)"    != "" ]; then
      dbset system.sound.type="hdmi"
   elif  [ "$(dbget system.hardware.alsa.digital.device)" != "" ]; then
      dbset system.sound.type="digital"
   else
      dbset system.sound.type="analog"
      if [ "$(dbget system.hardware.alsa.analog.device)" = "" ]; then
        dbset system.hardware.alsa.analog.device=0
        logger -t "find-alsa-devices" "No sound device found, using system.hardware.alsa.analog.device=0 (might be wrong)"
      fi
      if [ "$(dbget system.hardware.alsa.analog.card)" = "" ]; then
        dbset system.hardware.alsa.analog.card=0
        logger -t "find-alsa-devices" "No sound card found, using system.hardware.alsa.analog.card=0 (might be wrong)"
      fi
   fi
fi

