#!/bin/bash

eval $(DISPLAY=:1 xrandr -q|grep "*"|sed -e 's/[^0-9]*\([0-9]*\)x\([0-9]*\).*/X=\1; Y=\2/')

dbset system.x11.display.0.resolution.x=$X
dbset system.x11.display.0.resolution.y=$Y

if [ "x$(dbget system.x11.dualhead.enabled)" == "x1" ]; then
  eval $(DISPLAY=:1.1 xrandr -q|grep "*"|sed -e 's/[^0-9]*\([0-9]*\)x\([0-9]*\).*/X=\1; Y=\2/')

  dbset system.x11.display.1.resolution.x=$X
  dbset system.x11.display.1.resolution.y=$Y
else
  dbremove system.x11.display.1.resolution
fi
