#!/bin/bash

process-template --mode 755 --owner=vdr --group=vdr /var/lib/vdr/plugins/iptv/vlc2iptv

cat <<EOF >/var/lib/vdr/channels.conf
zdf-iptv;IPTV:4:S=0|P=0|F=EXT|U=vlc2iptv|A=4:I:0:256=27:257=deu@4;258=AC3@106:2321:0:28106:0:0:0
zdf_info-iptv;IPTV:5:S=0|P=0|F=EXT|U=vlc2iptv|A=5:I:0:256=27:257=deu@4;258=AC3@106:2321:0:28106:0:0:0
zdf_neo-iptv;IPTV:6:S=0|P=0|F=EXT|U=vlc2iptv|A=6:I:0:256=27:257=deu@4;258=AC3@106:2321:0:28106:0:0:0
zdf_kultur-iptv;IPTV:7:S=0|P=0|F=EXT|U=vlc2iptv|A=7:I:0:256=27:257=deu@4;258=AC3@106:2321:0:28106:0:0:0
NASA;IPTV:3:S=0|P=0|F=EXT|U=vlc2iptv|A=3:I:0:5:6:0:0:1:0:0:0
EOF

chown vdr:vdr /var/lib/vdr/channels.conf
