#!/bin/bash

SETUPCONF=/var/lib/vdr/setup.conf

if [ -e /etc/default/locale ]; then
. /etc/default/locale
fi

export LANG

process-template /etc/vdr/plugins/imagesources.conf

# default music dir

   if ! grep -q '^picselshow.MusicDir =.*' $SETUPCONF;then
     echo "picselshow.MusicDir = /media/Musik" >> $SETUPCONF
   else
     sed -i 's/picselshow.MusicDir =.*/picselshow.MusicDir = \/\media\/\Musik/g' $SETUPCONF;
   fi

# default picselshow.Max_OSDHeight = 1080

   if ! grep -q '^picselshow.Max_OSDHeight =.*' $SETUPCONF;then
     echo "picselshow.Max_OSDHeight = 1080" >> $SETUPCONF
   else
     sed -i 's/picselshow.Max_OSDHeight =.*/picselshow.Max_OSDHeight = 1080/g' $SETUPCONF;
   fi

# default picselshow.Max_OSDWidth = 1920

   if ! grep -q '^picselshow.Max_OSDWidth =.*' $SETUPCONF;then
     echo "picselshow.Max_OSDWidth = 1920" >> $SETUPCONF
   else
     sed -i 's/picselshow.Max_OSDWidth =.*/picselshow.Max_OSDWidth = 1920/g' $SETUPCONF;
   fi

