#!/bin/bash

for disp in ":1" ":1.1"; do
  LINE=$(xrandr -display $disp -q 2>/dev/null| head -n 1)
  SCREEN=$(echo $LINE | cut -d ":" -f 1 | cut -d " " -f 2)
  X=$(echo $LINE | cut -d ":" -f 2 | cut -d "," -f 2 | cut -d " " -f 3)
  Y=$(echo $LINE | cut -d ":" -f 2 | cut -d "," -f 2 | cut -d " " -f 5)
  if [ "x$X" != "x" ]; then
    dbset "system.x11.display.$SCREEN.resolution.x=$X"
    dbset "system.x11.display.$SCREEN.resolution.y=$Y"
  fi
done
