#!/bin/bash
if [[ "$(dbget system.x11.dualhead.enabled)" == "1" ]]; then
    if [[ -z "$(dbget vdr.tempdisplay)" ]]; then
      dbset "vdr.tempdisplay=.1"
    else
      dbremove "vdr.tempdisplay"
    fi
else
    dbremove "vdr.tempdisplay"
fi
